apiVersion: v1
description: |
  This chart installs the jx-test CronJob to garbage collect failed system test resources
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
name: jx-test
version: 0.0.45
home: https://github.com/jenkins-x-plugins/jx-test
appVersion: 0.0.45
